# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "arch_2dpass"

  input_dims: 4
  spatial_shape:
    - 1000
    - 1000
    - 60
  scale_list:
    - 2
    - 4
    - 8
    - 16

  hiden_size: 64
  num_classes: 25
  backbone_2d: resnet34
  pretrained2d: False # for finetuning set this to True

###################
## Dataset options
dataset_params:
  training_size: 19132
  dataset_type: "point_image_dataset_semkitti"
  pc_dataset_type: "Coda_test"
  collate_type: "collate_fn_default"
  ignore_label: 0
  label_mapping: "./config/label_mapping/coda_test.yaml"

  # 2D augmentation
  bottom_crop:
    - 480
    - 320
  color_jitter:
    - 0.4
    - 0.4
    - 0.4
  flip2d: 0.5
  image_normalizer:
    - [0.485, 0.456, 0.406]
    - [0.229, 0.224, 0.225]
  max_volume_space:
    - 50
    - 50
    - 2
  min_volume_space:
    - -50
    - -50
    - -4
  seg_labelweights:
    - 0
    - 35331535
    - 507127
    - 6769866
    - 26589757
    - 1365410
    - 2120036
    - 5660683
    - 8490475
    - 19117590
    - 40037811
    - 15765062
    - 3171941
    - 3911672 # metal grates
    - 331313
    - 6031076 # wood panel
    - 2073449
    - 3450963 # carpet
    - 7928482
    - 1547906
    - 1863293
    - 3851428
    - 48795
    - 160104
    - 418510

  train_data_loader:
    data_path: "/robodata/arthurz/Datasets/CODa_dev"
    batch_size: 8
    shuffle: True
    num_workers: 1
    rotate_aug: True
    flip_aug: True
    scale_aug: True
    transform_aug: True
    dropout_aug: True

  val_data_loader:
    data_path: "/robodata/arthurz/Datasets/CODa_dev"
    shuffle: False
    num_workers: 1

    # normal test
    batch_size: 8
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False


###################
## Train params
train_params:
  max_num_epochs: 64
  learning_rate: 0.24
  optimizer: SGD  # [SGD, Adam]
  lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-4

  lambda_seg2d: 1
  lambda_xm: 0.05
